services:
  postgres:
    image: postgres:14-alpine
    container_name: skylark_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skylarkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: skylark_mediamtx
    ports:
      - "8554:8554" # port forRTSP
      - "8888:8888" # port for WebRTC
      - "1935:1935" # port for RTMP
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: skylark_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped

  worker:
    build: ./worker
    container_name: skylark_worker
    ports:
      - "8080:8080"
    depends_on:
      - mediamtx
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: skylark_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: