services:
  postgres:
    image: postgres:14-alpine
    container_name: skylark_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skylarkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - skylark-app-net

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: skylark_mediamtx
    ports:
      - "8554:8554"
      - "8888:8888"
      - "1935:1935"
    restart: unless-stopped
    networks:
      - skylark-app-net

  backend:
    build: ./backend
    container_name: skylark_backend
    command: sh -c "npx prisma migrate deploy && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - skylark-app-net

  worker:
    build: ./worker
    container_name: skylark_worker
    ports:
      - "8080:8080"
    depends_on:
      - mediamtx
    restart: unless-stopped
    networks:
      - skylark-app-net

  frontend:
    build: ./frontend
    container_name: skylark_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - skylark-app-net

volumes:
  postgres_data:

networks:
  skylark-app-net:
    driver: bridge